default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: movies_development

test:
  <<: *default
  database: movies_test

production:
  <<: *default
  database: movies_production
